export const TestQuizQuestions = {
    data: [
        {
            id: 8,
            attributes: {
                fieldType: "card",
                fieldName: "choose-door-type",
                fieldTitle: "Choose Door Type",
                fieldTitleSize: "small",
                fieldRequired: false,
                createdAt: "2023-08-17T16:13:53.519Z",
                updatedAt: "2023-08-17T16:37:25.096Z",
                publishedAt: "2023-08-17T16:16:44.681Z",
                subQuestions: [
                    {
                        id: 1,
                        mainTitle: "Metal Door",
                        subTitle: "Interior and Exterior Use",
                        value: "1",
                        popular: false,
                        price: 200,
                        priceCurrency: "$",
                        default: false,
                        nextQuestion: 10,
                        image: {
                            url: "https://conexwest-doors.opserver.store/uploads/metal_door_0d3db7abc9.jpg",
                            alt: "Test alt",
                        },
                    },
                    {
                        id: 2,
                        mainTitle: "Wood Door",
                        subTitle: "Interior Use Only",
                        value: "1",
                        popular: false,
                        price: 150,
                        priceCurrency: "$",
                        default: false,
                        nextQuestion: null,
                        image: {
                            url: "https://conexwest-doors.opserver.store/uploads/wooden_door_7a82d3ea27.jpg",
                            alt: null,
                        },
                    },
                    {
                        id: 3,
                        mainTitle: "Metal Building Door",
                        subTitle: "Preengeniered steel",
                        value: "1",
                        popular: false,
                        price: 230,
                        priceCurrency: "$",
                        default: false,
                        nextQuestion: null,
                        image: {
                            url: "https://conexwest-doors.opserver.store/uploads/metal_building_steel_walk_door_d1546ca57e.jpg",
                            alt: null,
                        },
                    },
                    {
                        id: 4,
                        mainTitle: "Metal Frame Only",
                        subTitle: "Frame only  No door",
                        value: "1",
                        popular: false,
                        price: 110,
                        priceCurrency: "$",
                        default: false,
                        nextQuestion: null,
                        image: {
                            url: "https://conexwest-doors.opserver.store/uploads/welded_commercial_hollow_metal_door_frame_e1593365008886_480e1c3a6e.jpg",
                            alt: null,
                        },
                    },
                ],
            },
        },
        {
            id: 9,
            attributes: {
                fieldType: "multiple",
                fieldName: "door-with-frame",
                fieldTitle: "Door with frame",
                fieldTitleSize: "small",
                fieldRequired: false,
                createdAt: "2023-08-17T16:19:29.916Z",
                updatedAt: "2023-08-18T17:54:22.213Z",
                publishedAt: "2023-08-17T16:22:33.838Z",
                subQuestions: [
                    {
                        id: 1,
                        title: "Width",
                        fieldType: "radioButton",
                        questions: [
                            {
                                id: 1,
                                mainTitle: "12 inch",
                                subTitle: null,
                                value: "1",
                                popular: false,
                                price: 50,
                                priceCurrency: "$",
                                default: false,
                            },
                            {
                                id: 2,
                                mainTitle: "16 inch",
                                subTitle: null,
                                value: "1",
                                popular: false,
                                price: 60,
                                priceCurrency: "$",
                                default: false,
                            },
                            {
                                id: 3,
                                mainTitle: "18 inch",
                                subTitle: null,
                                value: "1",
                                popular: false,
                                price: 70,
                                priceCurrency: "$",
                                default: false,
                            },
                            {
                                id: 4,
                                mainTitle: "20 inch",
                                subTitle: null,
                                value: "1",
                                popular: false,
                                price: 80,
                                priceCurrency: "$",
                                default: false,
                            },
                            {
                                id: 5,
                                mainTitle: "22 inch",
                                subTitle: null,
                                value: "1",
                                popular: false,
                                price: 90,
                                priceCurrency: "$",
                                default: false,
                            },
                            {
                                id: 6,
                                mainTitle: "24 inch",
                                subTitle: null,
                                value: "1",
                                popular: false,
                                price: 100,
                                priceCurrency: "$",
                                default: false,
                            },
                        ],
                    },
                    {
                        id: 2,
                        title: "High",
                        fieldType: "radioButton",
                        questions: [
                            {
                                id: 7,
                                mainTitle: "30 inch",
                                subTitle: null,
                                value: "1",
                                popular: false,
                                price: 50,
                                priceCurrency: "$",
                                default: false,
                            },
                            {
                                id: 8,
                                mainTitle: "35 inch",
                                subTitle: null,
                                value: "1",
                                popular: false,
                                price: 70,
                                priceCurrency: "$",
                                default: false,
                            },
                            {
                                id: 9,
                                mainTitle: "40 inch",
                                subTitle: null,
                                value: "1",
                                popular: false,
                                price: 80,
                                priceCurrency: "$",
                                default: false,
                            },
                        ],
                    },
                    {
                        id: 3,
                        title: null,
                        fieldType: "checkbox",
                        questions: [
                            {
                                id: 10,
                                mainTitle: "Single door",
                                subTitle: null,
                                value: "Single door",
                                popular: false,
                                price: 200,
                                priceCurrency: "$",
                                default: false,
                            },
                            {
                                id: 11,
                                mainTitle: "Double door",
                                subTitle: null,
                                value: "1",
                                popular: false,
                                price: 400,
                                priceCurrency: "$",
                                default: false,
                            },
                        ],
                    },
                    {
                        id: 4,
                        title: null,
                        fieldType: "checkbox",
                        questions: [
                            {
                                id: 12,
                                mainTitle: "Interior",
                                subTitle: null,
                                value: "1",
                                popular: false,
                                price: 70,
                                priceCurrency: "$",
                                default: false,
                            },
                            {
                                id: 13,
                                mainTitle: "Exterior",
                                subTitle: null,
                                value: "1",
                                popular: false,
                                price: 140,
                                priceCurrency: "$",
                                default: false,
                            },
                        ],
                    },
                ],
            },
        },
        {
            id: 10,
            attributes: {
                fieldType: "card",
                fieldName: "select-metal-door-type",
                fieldTitle: "Select metal door type",
                fieldTitleSize: "small",
                fieldRequired: false,
                createdAt: "2023-08-17T16:33:44.517Z",
                updatedAt: "2023-08-17T16:37:56.336Z",
                publishedAt: "2023-08-17T16:33:53.313Z",
                subQuestions: [
                    {
                        id: 5,
                        mainTitle: "With frame",
                        subTitle: null,
                        value: "1",
                        popular: false,
                        price: 200,
                        priceCurrency: "$",
                        default: false,
                        nextQuestion: 9,
                        image: {
                            url: "https://conexwest-doors.opserver.store/uploads/metal_door_with_frame_e369cb4b10.jpg",
                            alt: null,
                        },
                    },
                    {
                        id: 6,
                        mainTitle: "Replacement",
                        subTitle: null,
                        value: "1",
                        popular: false,
                        price: 160,
                        priceCurrency: "$",
                        default: false,
                        nextQuestion: null,
                        image: {
                            url: "https://conexwest-doors.opserver.store/uploads/metal_door_replacement_875d623a4f.jpg",
                            alt: null,
                        },
                    },
                ],
            },
        },
    ],
    meta: {
        pagination: {
            page: 1,
            pageSize: 25,
            pageCount: 1,
            total: 3,
        },
        date: 1692597408901,
    },
};
