export const TestQuizQuestions = {
    data: [
        {
            id: 8,
            attributes: {
                fieldType: "card",
                fieldName: "choose-door-type",
                fieldTitle: "Choose Door Type",
                fieldTitleSize: "small",
                fieldRequired: false,
                createdAt: "2023-08-17T16:13:53.519Z",
                updatedAt: "2023-08-23T14:00:33.549Z",
                publishedAt: "2023-08-17T16:16:44.681Z",
                color: null,
                subQuestions: [
                    {
                        id: 1,
                        mainTitle: "Metal Doors",
                        subTitle: "Interior and Exterior Use",
                        value: "metal doors",
                        popular: false,
                        price: 200,
                        priceCurrency: "$",
                        default: false,
                        subfieldName: "metal-doors",
                        required: false,
                        nextQuestion: 10,
                        image: {
                            url: "https://conexwest-doors.opserver.store/uploads/metal_door_0d3db7abc9.jpg",
                            alt: "Test alt",
                        },
                    },
                    {
                        id: 2,
                        mainTitle: "Wood Door",
                        subTitle: "Interior Use Only",
                        value: "wood doors",
                        popular: false,
                        price: 150,
                        priceCurrency: "$",
                        default: false,
                        subfieldName: "wood-door",
                        required: false,
                        nextQuestion: 14,
                        image: {
                            url: "https://conexwest-doors.opserver.store/uploads/wooden_door_7a82d3ea27.jpg",
                            alt: null,
                        },
                    },
                    {
                        id: 3,
                        mainTitle: "Metal Building Door",
                        subTitle: "Preengeniered steel",
                        value: "metal building door",
                        popular: false,
                        price: 230,
                        priceCurrency: "$",
                        default: false,
                        subfieldName: "metal-building-door",
                        required: false,
                        nextQuestion: null,
                        image: {
                            url: "https://conexwest-doors.opserver.store/uploads/metal_building_steel_walk_door_d1546ca57e.jpg",
                            alt: null,
                        },
                    },
                    {
                        id: 4,
                        mainTitle: "Metal Frame Only",
                        subTitle: "Frame only  No door",
                        value: "metal frame only",
                        popular: false,
                        price: 110,
                        priceCurrency: "$",
                        default: false,
                        subfieldName: "metal-frame-only",
                        required: false,
                        nextQuestion: 12,
                        image: {
                            url: "https://conexwest-doors.opserver.store/uploads/welded_commercial_hollow_metal_door_frame_e1593365008886_480e1c3a6e.jpg",
                            alt: null,
                        },
                    },
                ],
                nextQuestion: null,
            },
        },
        {
            id: 9,
            attributes: {
                fieldType: "multiple",
                fieldName: "door-with-frame",
                fieldTitle: "Door with frame",
                fieldTitleSize: "big",
                fieldRequired: true,
                createdAt: "2023-08-17T16:19:29.916Z",
                updatedAt: "2023-08-24T18:44:08.221Z",
                publishedAt: "2023-08-17T16:22:33.838Z",
                color: null,
                subQuestions: [
                    {
                        id: 1,
                        fieldType: "radioButton",
                        fieldTitle: "Width",
                        subfieldName: "width",
                        fieldWidth: 100,
                        questions: [
                            {
                                id: 1,
                                mainTitle: "12 inch",
                                subTitle: "Sub title 12",
                                value: "12 inch",
                                popular: false,
                                price: 50,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: null,
                                required: null,
                            },
                            {
                                id: 2,
                                mainTitle: "16 inch",
                                subTitle: "16inch - big",
                                value: "16 inch",
                                popular: false,
                                price: 60,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: null,
                                required: null,
                            },
                            {
                                id: 3,
                                mainTitle: "18 inch",
                                subTitle: null,
                                value: "18 inch",
                                popular: false,
                                price: 70,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: null,
                                required: null,
                            },
                            {
                                id: 4,
                                mainTitle: "20 inch",
                                subTitle: null,
                                value: "20 inch",
                                popular: false,
                                price: 80,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: null,
                                required: null,
                            },
                            {
                                id: 5,
                                mainTitle: "22 inch",
                                subTitle: null,
                                value: "22 inch",
                                popular: false,
                                price: 90,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: null,
                                required: null,
                            },
                            {
                                id: 6,
                                mainTitle: "24 inch",
                                subTitle: null,
                                value: "24 inch",
                                popular: false,
                                price: 100,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: null,
                                required: null,
                            },
                        ],
                        required: false,
                    },
                    {
                        id: 2,
                        fieldType: "radioButton",
                        fieldTitle: "Height",
                        subfieldName: "height",
                        fieldWidth: 100,
                        questions: [
                            {
                                id: 7,
                                mainTitle: "30 inch",
                                subTitle: null,
                                value: "30",
                                popular: false,
                                price: 50,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: null,
                                required: null,
                            },
                            {
                                id: 8,
                                mainTitle: "35 inch",
                                subTitle: null,
                                value: "35",
                                popular: false,
                                price: 70,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: null,
                                required: null,
                            },
                            {
                                id: 9,
                                mainTitle: "40 inch",
                                subTitle: null,
                                value: "80",
                                popular: false,
                                price: 80,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: null,
                                required: null,
                            },
                        ],
                        required: false,
                    },
                    {
                        id: 3,
                        fieldType: "radio",
                        fieldTitle: null,
                        subfieldName: "f582b5eb-aff7-4ad1-b49f-935a1aaf4239",
                        fieldWidth: 50,
                        questions: [
                            {
                                id: 10,
                                mainTitle: "Single door",
                                subTitle: "default",
                                value: "Single door",
                                popular: false,
                                price: 200,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: null,
                                required: null,
                            },
                            {
                                id: 11,
                                mainTitle: "Double door",
                                subTitle: null,
                                value: "1",
                                popular: false,
                                price: 400,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: null,
                                required: null,
                            },
                            {
                                id: 16,
                                mainTitle: "triple door",
                                subTitle: "default too",
                                value: "tripleDoor",
                                popular: false,
                                price: 100,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: "triple door",
                                required: null,
                            },
                        ],
                        required: false,
                    },
                    {
                        id: 4,
                        fieldType: "radioButton",
                        fieldTitle: "IS_DEFAULT",
                        subfieldName: "is_default",
                        fieldWidth: 50,
                        questions: [
                            {
                                id: 12,
                                mainTitle: "Interior",
                                subTitle: "(default)",
                                value: "Interior",
                                popular: false,
                                price: 0,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: null,
                                required: null,
                            },
                            {
                                id: 13,
                                mainTitle: "Exterior",
                                subTitle: null,
                                value: "Exterior",
                                popular: false,
                                price: 0,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: null,
                                required: null,
                            },
                            {
                                id: 18,
                                mainTitle: "Air",
                                subTitle: "Air sub default",
                                value: "Airsubdefault",
                                popular: false,
                                price: 123,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: "Air",
                                required: null,
                            },
                        ],
                        required: false,
                    },
                    {
                        id: 5,
                        fieldType: "checkbox",
                        fieldTitle: "Checkbox title",
                        subfieldName: "checkbox-title",
                        fieldWidth: 50,
                        questions: [
                            {
                                id: 14,
                                mainTitle: "Checkbox title 1",
                                subTitle: "Checkbox sub default",
                                value: "Checkbox1",
                                popular: false,
                                price: 0,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: "Checkbox name 1",
                                required: null,
                            },
                            {
                                id: 15,
                                mainTitle: "Checkbox title 2",
                                subTitle: "Checkbox sub 2",
                                value: "Checkbox2",
                                popular: false,
                                price: 123,
                                priceCurrency: "$",
                                default: false,
                                subfieldName: "Checkbox name 2",
                                required: null,
                            },
                            {
                                id: 17,
                                mainTitle: "Checkbox title 3",
                                subTitle: "default",
                                value: "Checkboxname3",
                                popular: true,
                                price: 123,
                                priceCurrency: "$",
                                default: true,
                                subfieldName: "Checkbox name 3",
                                required: null,
                            },
                        ],
                        required: false,
                    },
                ],
                nextQuestion: 12,
            },
        },
        {
            id: 10,
            attributes: {
                fieldType: "card",
                fieldName: "select-metal-door-type",
                fieldTitle: "Select metal door type",
                fieldTitleSize: "small",
                fieldRequired: false,
                createdAt: "2023-08-17T16:33:44.517Z",
                updatedAt: "2023-08-22T09:44:39.094Z",
                publishedAt: "2023-08-17T16:33:53.313Z",
                color: null,
                subQuestions: [
                    {
                        id: 5,
                        mainTitle: "With frame",
                        subTitle: null,
                        value: "With frame",
                        popular: false,
                        price: 200,
                        priceCurrency: "$",
                        default: false,
                        subfieldName: "with-frame",
                        required: false,
                        nextQuestion: 9,
                        image: {
                            url: "https://conexwest-doors.opserver.store/uploads/metal_door_with_frame_e369cb4b10.jpg",
                            alt: null,
                        },
                    },
                    {
                        id: 6,
                        mainTitle: "Replacement",
                        subTitle: null,
                        value: "Replacement",
                        popular: false,
                        price: 160,
                        priceCurrency: "$",
                        default: false,
                        subfieldName: "replacement",
                        required: false,
                        nextQuestion: null,
                        image: {
                            url: "https://conexwest-doors.opserver.store/uploads/metal_door_replacement_875d623a4f.jpg",
                            alt: null,
                        },
                    },
                ],
                nextQuestion: null,
            },
        },
        {
            id: 11,
            attributes: {
                fieldType: "colorPicker",
                fieldName: "New Field name color",
                fieldTitle: "New Field Title color",
                fieldTitleSize: null,
                fieldRequired: true,
                createdAt: "2023-08-21T08:34:34.725Z",
                updatedAt: "2023-08-23T14:14:41.571Z",
                publishedAt: "2023-08-21T09:01:28.282Z",
                color: "#ff0000",
                subQuestions: [
                    {
                        id: 8,
                        mainTitle: "Choose color title",
                        subTitle: "Choose color SUBtitle",
                        value: "ChooseColorValue",
                        popular: true,
                        price: 123,
                        priceCurrency: "$",
                        default: false,
                        subfieldName: "choose-color-title",
                        required: false,
                        nextQuestion: null,
                    },
                ],
                nextQuestion: null,
            },
        },
        {
            id: 12,
            attributes: {
                fieldType: "card",
                fieldName: "TEST-IMAGES",
                fieldTitle: "TEST IMAGES",
                fieldTitleSize: "small",
                fieldRequired: false,
                createdAt: "2023-08-21T10:57:10.786Z",
                updatedAt: "2023-08-21T10:59:32.069Z",
                publishedAt: "2023-08-21T10:57:37.956Z",
                color: null,
                subQuestions: [
                    {
                        id: 9,
                        mainTitle: "TEST-IMAGES1",
                        subTitle: "TEST-IMAGES1",
                        value: "TEST-IMAGES1321",
                        popular: false,
                        price: 123,
                        priceCurrency: "$",
                        default: false,
                        subfieldName: null,
                        required: false,
                        nextQuestion: null,
                        image: {
                            url: "https://conexwest-doors.opserver.store/uploads/testing_image_kletka2_4990d8fdf9.png",
                            alt: null,
                        },
                    },
                    {
                        id: 10,
                        mainTitle: "TEST-IMAGES2",
                        subTitle: "TEST-IMAGES2",
                        value: "TEST-IMAGES2321",
                        popular: false,
                        price: 321,
                        priceCurrency: "$",
                        default: false,
                        subfieldName: null,
                        required: false,
                        nextQuestion: null,
                        image: {
                            url: "https://conexwest-doors.opserver.store/uploads/testing_image_kletka1_25abaa521e.png",
                            alt: null,
                        },
                    },
                ],
                nextQuestion: null,
            },
        },
        {
            id: 14,
            attributes: {
                fieldType: "checkbox",
                fieldName: "TEST_BRANCHING",
                fieldTitle: "TEST BRANCHING",
                fieldTitleSize: "small",
                fieldRequired: true,
                createdAt: "2023-08-22T12:50:23.030Z",
                updatedAt: "2023-08-22T16:38:04.902Z",
                publishedAt: "2023-08-22T16:38:04.894Z",
                color: null,
                subQuestions: [
                    {
                        id: 13,
                        mainTitle: "GO TO END",
                        subTitle: null,
                        value: "GOTOEND",
                        popular: false,
                        price: 123,
                        priceCurrency: "$",
                        default: false,
                        subfieldName: "go-to-end",
                        required: false,
                        nextQuestion: null,
                    },
                    {
                        id: 14,
                        mainTitle: "GO TO IMAGES",
                        subTitle: null,
                        value: "GOTOIMAGES",
                        popular: false,
                        price: 123,
                        priceCurrency: "$",
                        default: false,
                        subfieldName: "go-to-images",
                        required: false,
                        nextQuestion: 12,
                    },
                    {
                        id: 15,
                        mainTitle: "GO TO COLOR",
                        subTitle: null,
                        value: "GOTOCOLOR",
                        popular: false,
                        price: 123,
                        priceCurrency: "$",
                        default: false,
                        subfieldName: "go-to-color",
                        required: false,
                        nextQuestion: 11,
                    },
                ],
                nextQuestion: null,
            },
        },
    ],
    meta: {
        pagination: {
            page: 1,
            pageSize: 25,
            pageCount: 1,
            total: 6,
        },
        date: 1692902666497,
    },
};
